"""empty message

Revision ID: 730caa0e9195
Revises: 
Create Date: 2024-06-07 22:44:28.250820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730caa0e9195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('home_planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_planet'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('planet')
    # ### end Alembic commands ###
